import { glob, readFile, writeFile } from "node:fs/promises"

const directory = new URL("../src/gen/", import.meta.url)
const files = (await Array.fromAsync(glob("**/*_pb.ts", { cwd: directory }))).sort()
const exports = ["// Generated by scripts/generate-index.ts. Do not edit."]

for (const file of files) {
	const source = await readFile(new URL(file.replaceAll("\\", "/"), directory), "utf8")
	const symbols = new Map<string, boolean>()
	// Protobuf-ES emits top-level const/type declarations. Exclude file descriptors;
	// merge enum objects and their same-name types into one value re-export.
	for (const [, kind, name] of source.matchAll(/^export (const|type) (\w+)/gmu)) {
		if (name && !name.startsWith("file_")) {
			symbols.set(name, kind === "const" || symbols.get(name) === true)
		}
	}
	const names = [...symbols].map(([name, value]) => `${value ? "" : "type "}${name}`)
	if (names.length > 0) {
		exports.push(`export { ${names.join(", ")} } from "./${file.replaceAll("\\", "/")}"`)
	}
}

await writeFile(new URL("index.ts", directory), `${exports.join("\n")}\n`)
